### ISSUE TITLE
Remove tuskar-api doc?

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#1007]
Verify whether http://rdoproject.org/api/tuskar-api/ is still valid/current, and remove otherwise.

It is not liked from anywhere on the site, so I presume that it's obsolete.

**Comment by amoralej** [comment]
tuskar was deprecated and remove long time ago, we can remove it.

**Comment by snecklifter** [comment]
@rbowen this was merged so this can be closed?

**Comment by rbowen** [comment]
Yes. Fixed. Thanks, @snecklifter
