### ISSUE TITLE
The wiki is *GONE*

### ISSUE THREAD

**Issue by duck-rh** [redhat-openstack/website#1097]
The old wiki_* headers were removed in all pages but people are creating new pages with such headers (ok, just a single page).

So this is a double mistake because these headers were aimed at tracking which page came from the old wiki, which newly created pages clearly are not.

So the goal of this BR is:
* teach people to stop using these headers
* cleanup the new pages containing them

**Comment by pmkovar** [comment]
> cleanup the new pages containing them

This is a good long-term goal, but I'm not sure we need to have an issue open for that.

**Comment by duck-rh** [comment]
@pmkovar it has been like around 2 years the wiki is gone. I already cleaned up all pages in a previous PR a few moths ago. So I'm just expecting people to stop adding fields which were meant to track imported pages. These fields were never intended to be added by people anyway, only at the time of migration. This should have been achieved a long time ago.
