### ISSUE TITLE
Reorganize content

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#12]
There's quite a bit of content. It should be reorganized — especially for the stuff my conversion scripts couldn't figure out what to do with (pages without a category or a particular keyword), so it tossed them into `uncategorized`.

Here's a current listing of the file tree:
https://github.com/redhat-openstack/website/wiki/Document-tree-%282015-09-16%29

You can see a sortable, live list of pages ported from MediaWiki at:
http://beta.rdoproject.org/site/converted/

**Comment by garrett** [comment]
Also, the redirects page should be quite useful:
http://beta.rdoproject.org/site/redirects/

It lists pages by their original title and shows the URL fragment where the redirect would be pointed to. You can also click the little icon to view the URL on the original page. The first link tests the redirect (only works when deployed to an Apache server, like the beta site) and the second links directly.

As the redirect only takes the original and current locations into account, it's important to reorganize content _RIGHT NOW_ so that we would not break links when the site is final. (In other words, it won't track intermediate URLs, so take this opportunity to move and rename things _right now_.)

**Comment by garrett** [comment]
In addition, don't be afraid to search for things, including related pages. The search is quick and should help you find what you're looking for.

http://beta.rdoproject.org/search/

**Comment by garrett** [comment]
How is this coming along?

(Remember, you don't need to edit `redirects.yaml`; you just need to move around the files on disk.)

**Comment by rbowen** [comment]
we're done with this.
