### ISSUE TITLE
rdomanager doc points to dev version. no mention of stable version

### ISSUE THREAD

**Issue by marafa** [redhat-openstack/website#126]
http://docs.rdoproject.org/rdo-manager/master
immediately redirects to
https://repos.fedorapeople.org/repos/openstack-m/docs/master/
which tells you
"The RDO-Manager documentation has moved upstream. Click here to visit the new location."
which is
http://docs.openstack.org/developer/tripleo-docs/

the solution would be the page list
a) link to dev version documentation
b) link to current stable version documentation
c) link to previous current stable version documentation with a warning that it will EOL/EOS "very soon"(tm)

this is favoured to instead saying replace repo link with version name in the url as the documentation / steps may change with differing versions

**Comment by trown** [comment]
https://github.com/redhat-openstack/website/pull/163 resolves this.
