### ISSUE TITLE
Eliminate references to EOLed versions

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#128]
Find references to Havana and earlier, and either purge or update, as appropriate.

**Comment by apevec** [comment]
Icehouse too, RDO follows upstream lifecycle and Icehouse was EOLed

**Comment by rbowen** [comment]
http://beta.rdoproject.org/search/#icehouse

http://beta.rdoproject.org/search/#havana

http://beta.rdoproject.org/search/#grizzly

http://beta.rdoproject.org/search/#folsom Yikes!

http://beta.rdoproject.org/search/#essex Nothing problematic here

**Comment by rbowen** [comment]
Done
