### ISSUE TITLE
Re-add Table of Contents where needed

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#13]
Currently, Table of Contents is added manually. (I could change this...)

Please identify which pages need a ToC by using
http://beta.rdoproject.org/site/converted/

(Sorting by size probably helps.)

---

To add a Table of Contents, simply add the following to a file's frontmatter (the yaml-formatted metadata at the top of a document):

```yaml
layout: toc
```

In the event the automated ToC fails, you can manually add it in the relevant area of the page with the following Markdown code:

```markdown
1. toc
{:toc}
```

(Yes, you'd need to type it exactly like that. It gets replaced with a formatted ToC. You should not do this normally, however, as the `toc` layout will take care of it for you.)

**Comment by garrett** [comment]
How is this coming along? It's not needed for launch, but it would be nice to re-add ToC to (especially long-ish) pages that could use it. Remember, in 90+% of cases, all one needs to do is add `layout: toc` to the frontmatter at the top of a file.

**Comment by rbowen** [comment]
Got all of them, I believe.
