### ISSUE TITLE
Document RDO infrastructure

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#131]
Document which bits of RDO run where, preferably with diagrams showing the flow, and how various bits communicate with one another, and who owns which piece.

**Comment by dmsimard** [comment]
How do you propose we do the diagrams ? To properly version them it'd be preferable for them to not be either ASCII (e.g, http://asciiflow.com/) or binary (images). Perhaps graphviz (it looks like this: http://www.webgraphviz.com/) ? It doesn't look like there's anything built-in to middleman to help us with this. There's an unofficial extension here: https://github.com/HappyFunCorp/middleman-graphviz

**Comment by apevec** [comment]
There's diagram in unpublished (pending DLRN in ci.centos migration) blog by Alfredo https://github.com/redhat-openstack/website/blob/master/source/blog/2016-04-12-newbie-in-rdo-2-rdo-trunk-from-a-bird-s-eye-view.html.md

**Comment by rbowen** [comment]
This seems perhaps no longer relevant now that we're on software factory. Is that accurate?

**Comment by rbowen** [comment]
Sorry, @apevec , I missed your earlier comment. So, when we publish that blog post, we'll be able to close this ticket.
