### ISSUE TITLE
Needed Repos

### ISSUE THREAD

**Issue by abonillabeeche** [redhat-openstack/website#1352]
For RHEL 7 - these repos are needed

subscription-manager repos --enable rhel-7-server-extras-rpms
subscription-manager repos --enable rhel-7-server-optional-rpms

**Comment by spotz** [comment]
What page were these missing from?

**Comment by karelyatin** [comment]
I think in https://www.rdoproject.org/install/packstack/. Though they are listed in https://www.rdoproject.org/documentation/repositories/ would be good to list in https://www.rdoproject.org/install/packstack/ like it's done for RHEL8.
