### ISSUE TITLE
CentOS 8 - yum install network-scripts

### ISSUE THREAD

**Issue by eladeyal-intel** [redhat-openstack/website#1385]
in website/source/install/packstack.html.md

`service network restart` fails - propose to add `yum install network-scripts` ?

**Comment by spotz** [comment]
What OS was this failing on?

**Comment by eladeyal-intel** [comment]
Centos 8

**Comment by eladeyal-intel** [comment]
Apparantly this was fixed  in https://github.com/redhat-openstack/website/pull/1388 . Closing
