### ISSUE TITLE
Consolidate Heat docs

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#142]
We have two docs about deploying Heat - http://beta.rdoproject.org/install/deploying-heat-on-havana/ and http://beta.rdoproject.org/install/deploy-heat-and-launch-your-first-application/

I suspect that we don't actually need two separate docs. Combine, and update to latest version.

(See also #128)

**Comment by pmkovar** [comment]
Those page are gone. Instead, we should update https://www.rdoproject.org/install/deploy-an-application-with-heat/

**Comment by pmkovar** [comment]
Updated in #427, pending review.
