### ISSUE TITLE
GitHub is mis-cased in the edit image

### ISSUE THREAD

**Issue by jsoref** [redhat-openstack/website#1421]
![Github](https://github.com/redhat-openstack/website/raw/master/source/images/edit.png)

See [GitHub](https://github.com/about)

**Comment by spotz** [comment]
This image has been removed so this issue is closed.

**Comment by jsoref** [comment]
I'm not sure what you mean. The image is still very much in https://github.com/redhat-openstack/website/blob/master/source/images/edit.png and https://github.com/redhat-openstack/website/tree/master/source/images

If you either fix the content of the image or delete the image from the tip of `master`, then it's removed.

Until then, the file itself is an attractive nuisance -- someone may choose to use it thinking it's good, when it's in fact bad.

If you're no longer _using_ the file, then deleting it should be a pretty simple task.

**Comment by spotz** [comment]
Josh we removed the image from the site as part of another issue.

**Comment by jsoref** [comment]
Great, so you can delete the file from the repository, would it help if I created the PR for it?

**Comment by spotz** [comment]
Josh we switched to using Gerrit for patches and reviews. You're more than
welcome to put up a patch at https://review.rdoproject.org/r/ or I can do
it for you.

**Comment by jsoref** [comment]
Please do it for me, thanks.

**Comment by apevec** [comment]
https://review.rdoproject.org/r/c/rdo-website/+/32620
