### ISSUE TITLE
ERROR: EROFS READ ONLY FILE SYSTEM openstack

### ISSUE THREAD

**Issue by Joyia012** [redhat-openstack/website#1424]
Hi everyone,
I have deployed Openstack in Ubuntu server using this link [Openstack](https://ubuntu.com/tutorials/microstack-get-started#1-overview)

The installation was successful.
Now,
I want to change the openstack logo according to my requirement. It shows this error while modifying

`ERROR: EROFS READ ONLY FILE SYSTEM`

And also i have to pull my own OS-image in openstack. Can anybody help me in that.
Thanks in advance.

**Comment by amoralej** [comment]
Unfortunatelly we do not support or test deployment of OpenStack on ubuntu so i'd recommend to contact to ubuntu maintainers. Apparently there are some instructions to report bugs in https://ubuntu.com/tutorials/microstack-get-started#6-thats-all-folks
