### ISSUE TITLE
Consolidate the various TryStack docs

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#145]
There's a lot of overlap between:

http://beta.rdoproject.org/community/trystackfaq/

http://beta.rdoproject.org/community/trystack/

http://beta.rdoproject.org/documentation/using-rdo-on-trystack/

Please consolidate these, and update links throughout the site to this new resource. Or possibly put these docs on Trystack.org itself instead, or link from there to here.

**Comment by sadsfae** [comment]
We have moved all the trystack.org content to the OpenStack code repo and gating/CI (like other components).  https://github.com/openstack-infra/trystack-site (read-only mirror).  That's the authoritative source, and is updated via the upstream OpenStack Gerritt review process now.

**Comment by rbowen** [comment]
Ok, I'll consolidate the three pages, and point to the Trystack site for details, and possibly send some pull requests to that repo. Thanks!

**Comment by hguemar** [comment]
PR #150 by @rbowen fixes this issue
