### ISSUE TITLE
Remove irrelevant pages

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#15]
There are a few pages that are not relevant. They can often be determined by sorting all the converted wiki pages by size (so the smallest are at the top — these are the most likely culprits).
http://beta.rdoproject.org/site/converted/

Also, searches are useful, too:
http://beta.rdoproject.org/search/#draft
http://beta.rdoproject.org/search/#in%20progress

**Comment by rbowen** [comment]
Drafts include:

http://beta.rdoproject.org/uncategorized/packstack-with-multiple-compute-nodes/ ... I've asked beagles about this one.

http://beta.rdoproject.org/uncategorized/floating-ips-on-the-lab-network/ ... this one is beagles' also.

**Comment by garrett** [comment]
How is this coming along?

**Comment by rbowen** [comment]
I believe we're done with this, except in the sense that it's an ongoing task from release to release. Closing with respect to launch blockers.
