### ISSUE TITLE
Definition list of commonly used terms

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#159]
This should probably be split into sections, where one section is the release names, and the at least the other is common jargon, sorted alphabetically (probably).

(Or it could be broken down further, to networking, virtualization, etc.)

**Comment by meganeshkadam** [comment]
Hi Garett ! I would like to help with this . Please let me know how should I start ! :)

**Comment by rbowen** [comment]
It seems important that we reference http://docs.openstack.org/glossary/content/glossary.html and not duplicate things that are already there, but, rather, stick to defining terms that are "local" to RDO, like Delorean, or Packstack, and the like.

**Comment by meganeshkadam** [comment]
Rich, can you please explain more about this? I have gone through the reference but I am still not getting how to get started with this issue.

**Comment by rbowen** [comment]
We need to create a new document for this - I recommend putting it in the /rdo directory - and just start defining commonly used terms, while deferring upstream where possible.

**Comment by pmkovar** [comment]
Other than dlrn (or, rdo trunk?), packstack, what are some other terms we would like to cover on that page?
