### ISSUE TITLE
Better explanation of RDO Manager for the front page

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#160]
How would you better explain RDO Manager for the front page? (I can help in the summary, if needed.)

**Comment by apevec** [comment]
@trown @mburns72h please help!

**Comment by ibravo** [comment]
RDO Manager is an OpenStack installer geared to maximize the utilization of your Openstack infrastructure by adding and decreasing server capacity based on the needs of your Openstack cloud utilization.

RDO Manager is based on TripleO (Openstack on Openstack) and utilizes the idea of undercloud and overcloud deployments. RDO Manager deploys the undercloud server (One Physical or virtual server) with a basic All-in-One Openstack installation that will in turn, inventory, build, deploy and manage the overcloud (Your Cloud Infrastructure).

**Comment by cbrown2** [comment]
Thanks, have committed, see Pull Request #277, Build #453
