### ISSUE TITLE
Integrate blog & blogs

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#162]
The blog should show up on the front page, and there should probably be some blogs.rdoproject.org integration also.

**Comment by garrett** [comment]
You can see the start of blogs.rdoproject.org in this screenshot of my local WIP. I will probably make the full blogs look like this and perhaps collapse the external blogs.rdoproject.org to just a subject line and a link to the full thing.

![screen shot 2015-10-21 at 17 22 38](https://cloud.githubusercontent.com/assets/10246/10641857/527d1c6c-781b-11e5-94da-226801c92099.png)

**Comment by garrett** [comment]
Similar to #161, there's still no feedback at all here. Should I just scrap the effort then?

**Comment by rbowen** [comment]
The difficulty continues to be the large number of things that we want to put on the front page, and the lack of space for them that the layout allows.

Meanwhile, blogs.rdoproject.org has gone all but silent.

It would be nice to feature content from /blogs on the front page but the layout shown above results in lots and lots of scrolling. I think we should skip that, and instead try to work the latest tweets into the layout somewhere.
