### ISSUE TITLE
Links in footer

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/website#164]
USE IT -> Releases points to http://trunk.rdoproject.org/ which is NOT about releases but continuous build service! We should probably have a page with actual releases like upstream had ( https://wiki.openstack.org/wiki/Releases )

COMMUNITY -> Report a Problem points to https://bugzilla.redhat.com/buglist.cgi?quicksearch=RDO which gives lots of false positives. I guess it was meant to be https://bugzilla.redhat.com/enter_bug.cgi?product=RDO ?

**Comment by garrett** [comment]
Anything else that should be changed, added, or removed from the footer?

Please feel free to make patches too — what's there is almost verbatim from my mockups a few years ago — it was _supposed to_ have been changed, but it was only slightly altered.

**Comment by garrett** [comment]
(I asked for comments and modifications in a previous issue and again in my PR, before it was merged with very few changes.)

**Comment by garrett** [comment]
I've made a commit (see above) that addresses the trunk issue. It still needs a page to link to for all releases. (That's commented out.)

As for the community problem, there are two things:

1. The existing link is a way to view issues even if one is not logged in.
2. Your link is correct for _reporting_ a problem, which is actually what the text states.

I'll quickly make a commit that addresses these two items. (Adding a browse open issues link that goes to the current link — or something similar. And add a link to report a problem with RDO.)

**Comment by garrett** [comment]
So here's a list of things done, and things that need to be done, all related to this issue:

- [x] Added releases link placeholder (commented out)
- [x] Changed text to trunk build
- [x] Fixed bugzilla browse link URL
- [x] Added bugzilla browse link
- [x] Fixed bugzilla report link
- [x] Normalized text
- [ ] Add releases page to the site
- [ ] Fix releases link in the placeholder and uncomment

**Comment by garrett** [comment]
Added an issue for a releases page: #168.
