### ISSUE TITLE
Trunk.RDOproject.org has a broken style applied

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#165]
While I appreciate the effort, http://trunk.rdoproject.org/ has the style applied improperly.

It should have that content in the actual content area, not in the intro area. Also, the footer part should be in the footer, not the highlight section.

**Comment by garrett** [comment]
Firstly, what is on the page NOT _proper_ HTML. It's not semantic nor is it logical.

It should look more like this:

```html
<h2>RDO Trunk Development</h2>
<p><a href="https://rdoproject.org/packaging">Packaging documentation</a></p>

<h3>Lastest Build Reports</h3>
<ul>
  <li><a href="https://trunk.rdoproject.org/f22/report.html">Fedora 22</a></li>
  <li><a href="https://trunk.rdoproject.org/centos7/report.html">CentOS 7</a></li>
  <li><a href="https://trunk.rdoproject.org/centos7-liberty/report.html">CentOS 7 stable/Liberty</a></li>
  <li><a href="https://trunk.rdoproject.org/centos7-kilo/report.html">CentOS 7 stable/Kilo</a></li>
</ul>

<h3>Latest (untested!) delorean trunk repos</h3>
<ul>
  <li><a href="https://trunk.rdoproject.org/f22/current/">Fedora</a>, <a href="https://trunk.rdoproject.org/f22/current/delorean.repo">delorean repo</a></li>
  <li><a href="https://trunk.rdoproject.org/centos7/current/">CentOS 7</a>, <a href="https://trunk.rdoproject.org/centos7/current/delorean.repo">delorean repo</a></li>
</ul>

<h3>Latest (untested!) delorean stable repos</h3>
<ul>
  <li><a href="https://trunk.rdoproject.org/centos7-liberty/current/">CentOS 7 stable/Liberty</a>, <a href="https://trunk.rdoproject.org/centos7-liberty/current/delorean.repo">delorean repo</a></li>
  <li><a href="https://trunk.rdoproject.org/centos7-kilo/current/">CentOS 7 stable/Kilo</a>, <a href="https://trunk.rdoproject.org/centos7-kilo/current/delorean.repo">delorean repo</a></li>
</ul>
```

**Comment by garrett** [comment]
After mucking about in Firefox's dev tools, I reordered and used the above fixed HTML and produced this screenshot (which the page should be fixed to resemble).

![screen shot 2015-10-22 at 10 24 46](https://cloud.githubusercontent.com/assets/10246/10660424/3f2e83a8-78a7-11e5-8c64-9f2a002e37da.png)

**Comment by apevec** [comment]
Looks nice, thanks for fixing this landing page!
Source for trunk.rdo is maintained in https://github.com/redhat-openstack/trunk.rdoproject.org/ please send PR.

**Comment by garrett** [comment]
Oh, while peeking at the source, I see the CSS is hotlinked against the main site. This _will_ break when beta is flipped over to live.

**Comment by garrett** [comment]
I've made a PR. It should be merged and deployed at the exact moment the beta site is launched as official, else trunk.rdoproject.org will be broken (either with it being too early or too late).

https://github.com/redhat-openstack/trunk.rdoproject.org/pull/5

Bonus: In addition to the screenshot above, it also has navigation from the live site.

Also: The place to edit the file is marked between comments.

**Comment by apevec** [comment]
https://github.com/redhat-openstack/trunk.rdoproject.org/pull/5 was merged and deployed on trunk.rdo machine.
