### ISSUE TITLE
Releases page

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#168]
RDOproject.org needs a releases page similar to:
https://wiki.openstack.org/wiki/Releases

Ideally, this would be data that's easily editable and it generates the markup from the data, so no one has to muck around in table code.

* What's needed?
* Does anyone have a list of releases and the links for each?
* And is it (or can it) be easily programatically constructed (that is: follows a convention)?

**Comment by garrett** [comment]
This is needed as the last step (well, after adding a link to the page) to resolve #164.

**Comment by garrett** [comment]
...also, it's a good idea anyway.

**Comment by rbowen** [comment]
FWIW, the releases page is already at https://www.rdoproject.org/rdo/release-cadence/ it's just grossly out of date.
