### ISSUE TITLE
Reorganize "RDO Manager" docs

### ISSUE THREAD

**Issue by trown** [redhat-openstack/website#172]
We are maintaining a RDO specific fork of the upstream tripleo-docs at https://repos.fedorapeople.org/repos/openstack-m/rdo-manager-docs/liberty/ . It would be good to have a docs.rdoproject.org/rdo-manager/ link that points to https://repos.fedorapeople.org/repos/openstack-m/rdo-manager-docs/ .

**Comment by apevec** [comment]
Better option might be to publish directly on website server, same as /packaging/ is published from https://github.com/redhat-openstack/openstack-packaging-doc (on old site, missing on new box https://github.com/redhat-openstack/website/issues/181 )

@trown what are builddeps to build rdo-manager-docs?

**Comment by apevec** [comment]
On the new site, http://docs.rdoproject.org/rdo-manager/ currently redirects to https://repos.fedorapeople.org/repos/openstack-m/docs/ @trown is that good or bad? You can test it by putting
   54.225.229.160 www.rdoproject.org rdoproject.org
in your /etc/hosts
Excerpt from @mscherer 's playbook:
  - role: rdo_redirect_docs
    website_hostname: docs.rdoproject.org
    redirects:
    - { url: "/rdo-manager/", redirect: "https://repos.fedorapeople.org/repos/openstack-m/docs/" }

**Comment by apevec** [comment]
> You can test it by putting ... in your /etc/hosts

Ignore that part, new website is now in DNS

@mscherer I've sent you misc/ansible_osas/merge_requests/1 in your gitlib with the change requested by @trown

**Comment by apevec** [comment]
This is now out of date, on today's RDO meeting it was decided to consolidate RDO-Manager docs directly into website and link to upstream:
https://meetbot.fedoraproject.org/rdo/2016-01-20/rdo_meeting_(2016-01-20).2016-01-20-14.59.html
ACTION: trown hack on rdoproject.org rdo-manager docs (trown, 15:33:07)

@trown if you like, you can repurpose this ticket

**Comment by apevec** [comment]
docs.rdoproject.org/rdo-manager/ still redirects to the obsolete https://repos.fedorapeople.org/repos/openstack-m/docs/
Let's remove that redirect completely, there's now rdoproject.org/rdo-manager/
Also, topic on today's agenda[1] is RDO Manager -> tripleo rename, so we'll revisit this issue after the meeting:.

[1] https://etherpad.openstack.org/p/RDO-Meeting

**Comment by apevec** [comment]
We'll need to review all redirects, docs.rdoproject.org just for one path doesn't make sense.
Maybe docs.rdoproject.org -> www.rdoproject.org/documentation/ stripping path part of URL ?

**Comment by rbowen** [comment]
/rdo-manager now redirects to /tripleo and lots of files have been renamed. I'm no longer sure what we need to do here. Can someone revisit and summarize what's still ToDo?

**Comment by apevec** [comment]
@rbowen http://docs.rdoproject.org/rdo-manager/ still redirects to obsolete docs on FPO
TODOs as I see them:
* drop that obsolete redirect @mscherer ?
* make docs.rdoproject.org/* redirect to http://www.rdoproject.org/documentation/ @rbowen ?
* remove all obsolete content under https://repos.fedorapeople.org/repos/openstack-m/ to avoid confusion @trown ?

**Comment by mscherer** [comment]
so docs.rdoproject is hosted on aws.rdoproject.org, the old VM on EC2, is this normal ?

**Comment by trown** [comment]
I moved everything at https://repos.fedorapeople.org/repos/openstack-m/ that is not used to a .OLD dir. That way if we are wrong about it not being used, it can easily be restored.

**Comment by apevec** [comment]
@rbowen docs.rdoproject.org is an alias for aws.rdoproject.org.
^ I think aws.rdoproject.org can be removed and docs.rdo alias pointed to rcip.rdoproject.org ?

**Comment by pmkovar** [comment]
I think docs.rdoproject.org -> www.rdoproject.org/documentation would be best.

**Comment by rbowen** [comment]
Yes, the aws.rdoproject.org server, and no aliases to it, need to go away. I guess I thought we had done that. I'll take a look at the zone file as soon as I can.

**Comment by rbowen** [comment]
Hmm. Looks like someone has already taken care of this?

**Comment by rbowen** [comment]
the /tripleo section of the site now consists of one document (the quickstart) and links to upstream.
