### ISSUE TITLE
Some redirects not firing still

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#175]
https://rdoproject.org/repos/rdo-release.rpm and https://rdoproject.org/repos/ are not redirecting, while https://www.rdoproject.org/repos/rdo-release.rpm and https://www.rdoproject.org/repos/ are. So there's some configuration that's in the one vhost and not the other, although we should have across-the-board redirection from one of the vhosts to the other.

**Comment by rbowen** [comment]
... and now the rest of the redirects are no longer working. What's going on?

**Comment by rbowen** [comment]
See, for example:

wget --no-check-certificate -S https://www.rdoproject.org/Docs 
wget --no-check-certificate -S http://www.rdoproject.org/Docs 
wget --no-check-certificate -S https://rdoproject.org/Docs 
wget --no-check-certificate -S http://rdoproject.org/Docs 


--no-check-certificate because

WARNING: cannot verify rdoproject.org's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:

Which is perhaps another issue ...

**Comment by mscherer** [comment]
Ansible reverted some hotfix I did yesterday, hence the certificate issue. And redirect are now working fine as far as I can see.

**Comment by apevec** [comment]
Verified, all /Docs example URLs end up at https://www.rdoproject.org/documentation/
And naked release RPM urls works too/

**Comment by apevec** [comment]
NB verified  with
```
   54.225.229.160 www.rdoproject.org rdoproject.org
```
in /etc/hosts

**Comment by mscherer** [comment]
That's the old server. The new one is 209.132.179.87 (os1.rdoproject.org, vs aws.rdoproject.org )
