### ISSUE TITLE
Missing cert chain?

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#180]
[rbowen@localhost:rdo-website/source]$ wget -S https://rdoproject.org/Docs                                                         (10-22 14:48)
    --2015-10-22 14:48:37--  https://rdoproject.org/Docs
    Resolving rdoproject.org (rdoproject.org)... 209.132.179.87
    Connecting to rdoproject.org (rdoproject.org)|209.132.179.87|:443... connected.
    ERROR: cannot verify rdoproject.org's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
      Unable to locally verify the issuer's authority.
    To connect to rdoproject.org insecurely, use `--no-check-certificate'.

**Comment by apevec** [comment]
The same w/ curl and yum is using libcurl so QuickStart Step 1:
sudo yum install -y https://rdoproject.org/repos/rdo-release.rpm
fails.
https://www.rdoproject.org/repos/ works fine, so it must be cert setup mismatch for the naked vhost.

**Comment by mscherer** [comment]
The certificate is only for www.rdoproject.org, as it can be seen with the following command "openssl s_client -host rdoproject.org -port 443". If we want one for another domain, we need to ask for a new one, and this is gonna take a few days. I think it would be easier and faster to stay consistant and use www everywhere.

**Comment by apevec** [comment]
Hmm, seems to be working now (changing IP in /etc/hosts), there's only different response code

NEW site:
Connecting to rdoproject.org (rdoproject.org)|209.132.179.87|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found

OLD site:
Connecting to rdoproject.org (rdoproject.org)|54.225.229.160|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 301 Moved Permanently

**Comment by mscherer** [comment]
So maybe I am reading wrong the openssl output. But I do not understand why it would be working, as I see no indication of me requesting a 2nd domain name ( but SSL have always been my weak point ).

**Comment by apevec** [comment]
AFAICT our cert is good for naked, https://www.digicert.com/help/ says:
Common Name = www.rdoproject.org
Subject Alternative Names = www.rdoproject.org, rdoproject.org
So looks like this can be closed now after CA bundle configuration was fixed in naked vhost.
