### ISSUE TITLE
Packaging docs missing

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#181]
On the old server, we have  `Alias /packaging /var/www/html/packaging` and /var/www/html/packaging is a checkout of https://github.com/redhat-openstack/openstack-packaging-doc 

This is missing on the new server. This is fairly urgent.

Can we do a checkout within a checkout, a la svn?

**Comment by apevec** [comment]
It's not just a checkout, there was a cron job on the old webserver publishing periodically from that git repo, asciidoctor must be installed on the box:
https://github.com/redhat-openstack/openstack-packaging-doc#rendering

**Comment by mscherer** [comment]
So this is working on the new site, even if the page I see is strangely lacking any stylesheet. So I get HTML, not sure if I get all.

**Comment by apevec** [comment]
@garrett is this the same issue you fixed for trunk.rdoproject.org https://github.com/redhat-openstack/trunk.rdoproject.org/pull/5 ?

**Comment by apevec** [comment]
Confirmed with
```
54.225.229.160 www.rdoproject.org rdoproject.org
```
in /etc/hosts: HTML is there, styling needs to be updated for new site.

**Comment by apevec** [comment]
I'll try to adjust styling based on Garrett's trunk.rdo fix.

**Comment by apevec** [comment]
So this is not the same as trunk.rdo issue (styling stil needs to be adjusted but this a separate issue known from before) rather that https://www.rdoproject.org/packaging/stylesheets/rdo.css is 404
@mscherer please check the build job is generating all files and they're all of html/ is copied recursively to the webserving location.

**Comment by mscherer** [comment]
So I hotfixed it by hand, but the problem is that the makefile do not copy the stylesheets in the file:
```
 $ make clean ; make ;ls -a html/stylesheets
rm -rf html
mkdir -p html
asciidoctor -b html5 \
	-a linkcss -a stylesheet=rdo.css -a stylesdir=stylesheets \
	-a icons -a imagesdir=images -a iconsdir=images/icons \
	-o html/rdo-packaging.html doc/rdo-packaging.txt
asciidoctor -b html5 \
	-a linkcss -a stylesheet=rdo.css -a stylesdir=stylesheets \
	-a icons -a imagesdir=images -a iconsdir=images/icons \
	-o html/index.html doc/index.txt
cp -r images html/
.  ..
```
