### ISSUE TITLE
Missing stats directory

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#182]
On the old server, /stats is a checkout of `https://github.com/Bitergia/redhat-rdo-dashboard.git`

This is missing on the new server.

**Comment by garrett** [comment]
I believe @mscherer would need to set this up, with some sort of overlay at the httpd level, I guess, so the checkouts don't conflict.

**Comment by mscherer** [comment]
Yep, I did added that in ansible, but didn't had time to check for correctness (besides "it deploy ok") due to others fires. I will take a look

**Comment by mscherer** [comment]
Ok so it was just a missing / in various apache configuration. It now work fine.

**Comment by apevec** [comment]
rdoproject.org/stats/ works but rdoproject.org/stats is 404

**Comment by rbowen** [comment]
For me, /stats redirects to /stats/ which works fine. I take it this is fixed now?

**Comment by rbowen** [comment]
The problem here is likely that we have:

Alias /stats/

rather than

Alias /stats

And, similarly for /packaging

**Comment by mscherer** [comment]
Ok, this one should be fixed now.

**Comment by apevec** [comment]
Verified. And we're live!
www.rdoproject.org is an alias for os1.rdoproject.org.
os1.rdoproject.org has address 209.132.179.87
