### ISSUE TITLE
Update planet.openstack.org pointer to blog

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#183]
Ensure that planet.openstack.org is pointing to the right location for the new RDO blog.

**Comment by garrett** [comment]
...but a blog is not a planet...?

**Comment by mscherer** [comment]
And what is the right location ?

**Comment by rbowen** [comment]
Patch sent to planet.openstack.org - https://review.openstack.org/#/c/239774/

**Comment by rbowen** [comment]
Garrett, I don't understand your comment. Can you elaborate?

**Comment by mscherer** [comment]
I think he misunderstood the first comment ( and so did I, but it was clearer once I see the patch ).

**Comment by rbowen** [comment]
Change merged.
