### ISSUE TITLE
Enable mod_speling case-insensitive mode

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#193]
A number of the redirects that we're relying on right now could be resolved if we enable mod_speling's case insensitive mode. (Although it's possible that the 404 search handling of Middleman might interfere.)

To do this, we need to enable the module in the main httpd config

LoadModule speling_module modules/mod_speling.so
CheckCaseOnly on

we can then remove redirects that merely check case, like the Quickstart and QuickStart ones.

**Comment by mscherer** [comment]
Ok, I added it, can you check if it doesn't break anything ?

**Comment by rbowen** [comment]
Closing. Thanks.
