### ISSUE TITLE
Delete files are not removed

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#227]
https://www.rdoproject.org/rdo/about-rdo/ has been removed from git but still exists on the server. What's up with that?

**Comment by mscherer** [comment]
we do not use --delete-after on rsync, I fixed that upstream and I need to deploy the new role or push the change in prod (https://github.com/OSAS/ansible-role-middleman_builder/commit/5b8674b2b8414b66f691369e6d625a04c49d1f3f)

**Comment by rbowen** [comment]
It appears that this has now been resolved.
