### ISSUE TITLE
 https://www.rdoproject.org/packaging/rdopkg/ is missing

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/website#237]
@yac how was it published on the old site?

**Comment by rbowen** [comment]
Cron job on old server that does this:


#!/bin/bash

set -ex

rm -rf /var/packaging/html

cd /var/packaging/openstack-packaging-doc/
git fetch origin
git reset --hard origin/master
make clean all
cp -r html ../

cd /var/packaging/rdopkg
git fetch origin
git reset --hard origin/master
cd doc
make clean html
cp -r html ../../html/rdopkg

cd /var/packaging
rsync --delete -acOv html/ /var/www/html/packaging

**Comment by mscherer** [comment]
I would need the git repository to be used, cause git fetch is not gonna work without it :)

**Comment by rbowen** [comment]
[rbowen@ip-10-12-182-46 openstack-packaging-doc]$ git remote -v
origin	https://github.com/redhat-openstack/openstack-packaging-doc (fetch)
origin	https://github.com/redhat-openstack/openstack-packaging-doc (push)

**Comment by mscherer** [comment]
And for the rdopkg repo ?

**Comment by mscherer** [comment]
Also, is it urgent ( cause I am in meeting for 2 days )

**Comment by rbowen** [comment]
This issue got dropped over new years break. Do you have all the information you need to move on this, or are we still missing something?

**Comment by mscherer** [comment]
I still need the rdopkg repo url.

**Comment by rbowen** [comment]
Looks like it's at https://github.com/redhat-openstack/rdopkg

**Comment by mscherer** [comment]
So that's done (took me a while for various reasons, like order of alias...): https://www.rdoproject.org/packaging/rdopkg/rdopkg.1.html

But there is no index.html file, shall I enable the Indexes in apache ?

**Comment by apevec** [comment]
Let's redirect /packaging/rdopkg/ to https://www.rdoproject.org/packaging/rdopkg/rdopkg.1.html

**Comment by mscherer** [comment]
Ok sorry to not have fixed this one earlier, it is good now.
