### ISSUE TITLE
Error on "mariadb"

### ISSUE THREAD

**Issue by sonytalen** [redhat-openstack/website#241]
Has anyone met such errors ?  It interrupts at “mariadb.pp”

I found that also other guy have similar issue. https://bugzilla.redhat.com/show_bug.cgi?id=1268868

But no answer so far.

Adding AMQP manifest entries                         [ DONE ]
Adding MariaDB manifest entries                      [ DONE ]
Fixing Keystone LDAP config parameters to be undef if empty[ DONE ]
Adding Keystone manifest entries                     [ DONE ]
Adding Glance Keystone manifest entries              [ DONE ]
Adding Glance manifest entries                       [ DONE ]
Adding Cinder Keystone manifest entries              [ DONE ]
Checking if the Cinder server has a cinder-volumes vg[ DONE ]
Adding Cinder manifest entries                       [ DONE ]
Adding Nova API manifest entries                     [ DONE ]
Adding Nova Keystone manifest entries                [ DONE ]
Adding Nova Cert manifest entries                    [ DONE ]
Adding Nova Conductor manifest entries               [ DONE ]
Creating ssh keys for Nova migration                 [ DONE ]
Gathering ssh host keys for Nova migration           [ DONE ]
Adding Nova Compute manifest entries                 [ DONE ]
Adding Nova Scheduler manifest entries               [ DONE ]
Adding Nova VNC Proxy manifest entries               [ DONE ]
Adding OpenStack Network-related Nova manifest entries[ DONE ]
Adding Nova Common manifest entries                  [ DONE ]
Adding Neutron VPNaaS Agent manifest entries         [ DONE ]
Adding Neutron FWaaS Agent manifest entries          [ DONE ]
Adding Neutron LBaaS Agent manifest entries          [ DONE ]
Adding Neutron API manifest entries                  [ DONE ]
Adding Neutron Keystone manifest entries             [ DONE ]
Adding Neutron L3 manifest entries                   [ DONE ]
Adding Neutron L2 Agent manifest entries             [ DONE ]
Adding Neutron DHCP Agent manifest entries           [ DONE ]
Adding Neutron Metering Agent manifest entries       [ DONE ]
Adding Neutron Metadata Agent manifest entries       [ DONE ]
Checking if NetworkManager is enabled and running    [ DONE ]
Adding OpenStack Client manifest entries             [ DONE ]
Adding Horizon manifest entries                      [ DONE ]
Adding Swift Keystone manifest entries               [ DONE ]
Adding Swift builder manifest entries                [ DONE ]
Adding Swift proxy manifest entries                  [ DONE ]
Adding Swift storage manifest entries                [ DONE ]
Adding Swift common manifest entries                 [ DONE ]
Adding Heat manifest entries                         [ DONE ]
Adding MongoDB manifest entries                      [ DONE ]
Adding Redis manifest entries                        [ DONE ]
Adding Ceilometer manifest entries                   [ DONE ]
Adding Ceilometer Keystone manifest entries          [ DONE ]
Adding Nagios server manifest entries                [ DONE ]
Adding Nagios host manifest entries                  [ DONE ]
Adding post install manifest entries                 [ DONE ]
Copying Puppet modules and manifests                 [ DONE ]
Applying 192.168.168.188_prescript.pp
192.168.168.188_prescript.pp:                        [ DONE ]
Applying 192.168.168.188_chrony.pp
192.168.168.188_chrony.pp:                           [ DONE ]
Applying 192.168.168.188_amqp.pp
Applying 192.168.168.188_mariadb.pp
192.168.168.188_amqp.pp:                             [ DONE ]
192.168.168.188_mariadb.pp:                       [ ERROR ]
Applying Puppet manifests                         [ ERROR ]

ERROR : Error appeared during Puppet run: 192.168.168.188_mariadb.pp
Error: Execution of '/usr/bin/rpm -e mariadb-server-5.5.44-1.el7_1.x86_64' returned 1: error: Failed dependencies:
You will find full trace in log /var/tmp/packstack/20151120-163002-vm8LhT/manifests/192.168.168.188_mariadb.pp.log
Please check log file /var/tmp/packstack/20151120-163002-vm8LhT/openstack-setup.log for more information
Additional information:
* File /root/keystonerc_admin has been created on OpenStack client host 192.168.168.188. To use the command line tools you need to source the file.
* NOTE : A certificate was generated to be used for ssl, You should change the ssl certificate configured in /etc/httpd/conf.d/ssl.conf on 192.168.168.188 to use a CA signed cert.
* To access the OpenStack Dashboard browse to https://192.168.168.188/dashboard .
Please, find your login credentials stored in the keystonerc_admin in your home directory.
* To use Nagios, browse to http://192.168.168.188/nagios username: nagiosadmin, password: 0d24dc02291f404b

**Comment by garrett** [comment]
@sonytalen: This issue tracker is specifically for the website, not for RDO itself.

You can find the correct location in the footer of at the bottom of ther RDO website at https://rdoproject.org/ — the two links in question are:

- [Browse open issues](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&product=RDO&query_format=advanced)
- [Report a problem](https://bugzilla.redhat.com/enter_bug.cgi?product=RDO)

There's also a [troubleshooting page on rdoproject.org](https://www.rdoproject.org/troubleshooting/) and there is [an active and useful forum with an RDO-specific section at ask.openstack.org](https://ask.rdoproject.org/) — it's also in the footer too, as "Ask (Q&A)".

Hopefully one of the above links helps out!
