### ISSUE TITLE
Encourage doc//website editing ?

### ISSUE THREAD

**Issue by dmsimard** [redhat-openstack/website#244]
Something I really like about the layout of readthedocs.org is that on every page you have a "Edit on Github" button, example at the top right: http://dnf.readthedocs.org/en/latest/index.html

Would be cool to have a way to implement something similar for our documentation (or perhaps every page?)

I'm not talking about a cheesy "fork on github" banner but a link to the source could be great.

**Comment by apevec** [comment]
There is "Edit this page on GitHub" on the bottom of each page.

**Comment by dmsimard** [comment]
Oh man, I feel silly now. I just expected it to be on the top instead. I'll close this and go hide now.

**Comment by apevec** [comment]
Not stilly at all, it is indeed hard to find.
@rbowen @garrett  what about moving "Edit this page" to the top?

**Comment by rbowen** [comment]
It seems that we had that briefly, and then it disappeared. I wonder what that's about. I'll see if I can hunt down that particular commit and what happened afterwards.

**Comment by rbowen** [comment]
Ah. It appears that this was intentional, as per discussion in #100, that this be removed. @garrett do you have a thought of where we could put this at the top of the page for greater visibility?

**Comment by rbowen** [comment]
I've added a "Edit on Github" banner to the page header, linking directly to the inline editor for that page. I'm sure that someone with more graphics-fu can make the image file look better, but it does the job.
