### ISSUE TITLE
QuickStart does not highlight/encourage use of CentOS Virt SIG

### ISSUE THREAD

**Issue by xsgordon** [redhat-openstack/website#245]
The CentOS Virt Sig repository provides newer and more up to date builds of qemu-kvm for use with oVirt and OpenStack. These are highly recommended as increasingly new functionality (e.g. some NUMA changes in Liberty) wont work without them.

The QuickStart [1] should include enabling the centos-release-qemu-ev repository from CentOS Extras:

      http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-qemu-ev-1.0-1.el7.noarch.rpm

Which will in turn configure the system to retrieve from e.g. http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/ where the up to date packages are available. Ideally this should eventually be done my rdo-release and/or the automated deployment tools.

[1] 
https://github.com/redhat-openstack/website/blob/master/source/install/quickstart.html.md

**Comment by rbowen** [comment]
I wonder if you might be willing to send a pull request of where you want this information to appear in the flow of the quickstart page:

https://github.com/redhat-openstack/website/edit/master/source/install/quickstart.html.md

Thanks.

**Comment by apevec** [comment]
Decision from meeting yesterday was to add dep on Virt SIG repo in rdo-release rpm and in delorean-deps.repo https://github.com/redhat-openstack/delorean-instance/issues/22

**Comment by rbowen** [comment]
Can someone revisit and say what actually still needs done here? It's no longer clear.

**Comment by apevec** [comment]
Both rdo-release and delorean-deps changes are still TODO.

**Comment by apevec** [comment]
So we can't really add it in rdo-release RPM b/c that one is targeting also non-CentOS EL distros.
It was added in centos-release-openstack-mitaka: https://github.com/apevec/centos-release-openstack/commit/ebd91a4c7dc8c5a722026b4075bb262286b45c77

**Comment by pmkovar** [comment]
I've added `yum install centos-release-openstack-mitaka` in https://github.com/redhat-openstack/website/blob/master/source/install/quickstart.html.md for CentOS users.

I believe that fixes this issue but please reopen if it does not.
