### ISSUE TITLE
Documentation page does not render properly

### ISSUE THREAD

**Issue by vagelim** [redhat-openstack/website#251]
This page: https://www.rdoproject.org/documentation/rabbitmq/
does not render properly in Chrome version 46.0.2490.86 (64-bit) on MacOSX 10.11

As you can see in the [screenshot](http://imgur.com/uANdqaB), the text on the left side of the page is cut off.

**Comment by mscherer** [comment]
I suspect that the problem is the 3 div at the start of the file, not sure what they are for since the styling is done by middleman.
