### ISSUE TITLE
Broken link to https://www.rdoproject.org/documentation/frequently-asked-questions/

### ISSUE THREAD

**Issue by vaneldik** [redhat-openstack/website#284]
The "Ask and Answer" section on https://www.rdoproject.org/community/ contains a link to a non-existent page from

>    Check our Frequently Asked Questions (FAQ) page for answers to common questions

I could not find an obvious solution for this.

Thanks!

**Comment by rbowen** [comment]
The FAQ is at /rdo/faq/ - https://www.rdoproject.org/rdo/faq/

**Comment by vaneldik** [comment]
Thanks, PR at https://github.com/redhat-openstack/website/pull/290

Closing this issue.
