### ISSUE TITLE
Update Upgrade doc to reflect current reality

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#328]
https://www.rdoproject.org/install/upgrading-rdo/ refers to Havana.

Meanwhile, we also have https://www.rdoproject.org/install/upgrading-rdo-to-icehouse/

**Comment by pmkovar** [comment]
@rbowen I'd take this one. I guess I need some special perms to assign this bug to myself, right?

**Comment by apevec** [comment]
@pmkovar invite sent for the "docs" team - you should have "assign yourself" after you join

**Comment by pmkovar** [comment]
@apevec Thanks!

**Comment by pmkovar** [comment]
I think we can now close this. Old pages on upgrading have been removed or updated for Mitaka.
