### ISSUE TITLE
Fix Open vSwitch and tcpdump links

### ISSUE THREAD

**Issue by ariksa** [redhat-openstack/website#336]
Just after the Toolchain header, the links to Open vSwitch and tcpdump are not working.
The first problem is that the links have https, while the sites do not support https.
The second is that Open vSwitch site probably has changed its documentation location.

**Comment by rbowen** [comment]
This appears to be referring to https://www.rdoproject.org/troubleshooting/networking/

**Comment by ariksa** [comment]
The merge didn't fix all the links.
These still don't work, because openvswitch.org has probably changed its documentation location.
* ovs-vsctl
* ovs-ofctl
* ovs-dpctl

**Comment by pmkovar** [comment]
@ariksa I've fixed those in https://github.com/redhat-openstack/website/commit/19d88e3d98095072e58aa7d75778e53474805302.

Please let us know if there are more issues. Thanks.
