### ISSUE TITLE
the paste file is empty

### ISSUE THREAD

**Issue by chenleji** [redhat-openstack/website#383]
[root@test ~]# packstack --answer-file=packstack-answers-20160217-100038.txt
Welcome to the Packstack setup utility

The installation log file is available at: /var/tmp/packstack/20160217-102455-CqXnHv/openstack-setup.log

Installing:
Clean Up                                             [ DONE ]
Discovering ip protocol version                      [ DONE ]
Setting up ssh keys                                  [ DONE ]
Preparing servers                                    [ DONE ]
Pre installing Puppet and discovering hosts' details [ DONE ]
Adding pre install manifest entries                  [ DONE ]
Setting up CACERT                                    [ DONE ]
Adding AMQP manifest entries                         [ DONE ]
Adding MariaDB manifest entries                      [ DONE ]
Fixing Keystone LDAP config parameters to be undef if empty[ DONE ]
Adding Keystone manifest entries                     [ DONE ]
Adding Glance Keystone manifest entries              [ DONE ]
Adding Glance manifest entries                       [ DONE ]
Adding Cinder Keystone manifest entries              [ DONE ]
Checking if the Cinder server has a cinder-volumes vg[ DONE ]
Adding Cinder manifest entries                       [ DONE ]
Adding Nova API manifest entries                     [ DONE ]
Adding Nova Keystone manifest entries                [ DONE ]
Adding Nova Cert manifest entries                    [ DONE ]
Adding Nova Conductor manifest entries               [ DONE ]
Creating ssh keys for Nova migration                 [ DONE ]
Gathering ssh host keys for Nova migration           [ DONE ]
Adding Nova Compute manifest entries                 [ DONE ]
Adding Nova Scheduler manifest entries               [ DONE ]
Adding Nova VNC Proxy manifest entries               [ DONE ]
Adding OpenStack Network-related Nova manifest entries[ DONE ]
Adding Nova Common manifest entries                  [ DONE ]
Adding Neutron VPNaaS Agent manifest entries         [ DONE ]
Adding Neutron FWaaS Agent manifest entries          [ DONE ]
Adding Neutron LBaaS Agent manifest entries          [ DONE ]
Adding Neutron API manifest entries                  [ DONE ]
Adding Neutron Keystone manifest entries             [ DONE ]
Adding Neutron L3 manifest entries                   [ DONE ]
Adding Neutron L2 Agent manifest entries             [ DONE ]
Adding Neutron DHCP Agent manifest entries           [ DONE ]
Adding Neutron Metering Agent manifest entries       [ DONE ]
Adding Neutron Metadata Agent manifest entries       [ DONE ]
Adding Neutron SR-IOV Switch Agent manifest entries  [ DONE ]
Checking if NetworkManager is enabled and running    [ DONE ]
Adding OpenStack Client manifest entries             [ DONE ]
Adding Horizon manifest entries                      [ DONE ]
Adding Provisioning Demo manifest entries            [ DONE ]
Adding Provisioning Demo bridge manifest entries     [ DONE ]
Adding Provisioning Glance manifest entries          [ DONE ]
Adding Nagios server manifest entries                [ DONE ]
Adding Nagios host manifest entries                  [ DONE ]
Adding post install manifest entries                 [ DONE ]
Copying Puppet modules and manifests                 [ DONE ]
Applying 172.16.0.82_prescript.pp
172.16.0.82_prescript.pp:                            [ DONE ]       
Applying 172.16.0.82_amqp.pp
Applying 172.16.0.82_mariadb.pp
172.16.0.82_amqp.pp:                                 [ DONE ]     
172.16.0.82_mariadb.pp:                              [ DONE ]     
Applying 172.16.0.82_keystone.pp
Applying 172.16.0.82_glance.pp
Applying 172.16.0.82_cinder.pp
172.16.0.82_keystone.pp:                             [ DONE ]      
**172.16.0.82_glance.pp:                            [ ERROR ]        
Applying Puppet manifests                         [ ERROR ]**

**ERROR : Error appeared during Puppet run: 172.16.0.82_glance.pp
Error: Could not start Service[glance-registry]: Execution of '/usr/bin/systemctl start openstack-glance-registry' returned 1: Job for openstack-glance-registry.service failed. See 'systemctl status openstack-glance-registry.service' and 'journalctl -xn' for details.**
You will find full trace in log /var/tmp/packstack/20160217-102455-CqXnHv/manifests/172.16.0.82_glance.pp.log
Please check log file /var/tmp/packstack/20160217-102455-CqXnHv/openstack-setup.log for more information

--------------------------------------------------------------------------------------------------
I check the glance registry log file, and found the error msg as follow:

[root@test ~]# tailf /var/log/glance/registry.log 
2016-02-17 10:31:45.782 20722 ERROR glance.common.config [-] **Unable to load glance-registry-keystone from configuration file /etc/glance/glance-registry-paste.ini.**
Got: LookupError("No section 'glance-registry-keystone' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /etc/glance/glance-registry-paste.ini",)
2016-02-17 10:31:46.143 20732 ERROR glance.common.config [-] Unable to load glance-registry-keystone from configuration file /etc/glance/glance-registry-paste.ini.
Got: LookupError("No section 'glance-registry-keystone' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /etc/glance/glance-registry-paste.ini",)
2016-02-17 10:31:46.508 20742 ERROR glance.common.config [-] Unable to load glance-registry-keystone from configuration file /etc/glance/glance-registry-paste.ini.
Got: LookupError("No section 'glance-registry-keystone' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /etc/glance/glance-registry-paste.ini",)
2016-02-17 10:31:46.871 20752 ERROR glance.common.config [-] Unable to load glance-registry-keystone from configuration file /etc/glance/glance-registry-paste.ini.
Got: LookupError("No section 'glance-registry-keystone' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /etc/glance/glance-registry-paste.ini",)
2016-02-17 10:31:47.230 20762 ERROR glance.common.config [-] Unable to load glance-registry-keystone from configuration file /etc/glance/glance-registry-paste.ini.
Got: LookupError("No section 'glance-registry-keystone' (prefixed by 'app' or 'application' or 'composite' or 'composit' or 'pipeline' or 'filter-app') found in config /etc/glance/glance-registry-paste.ini",)

---------------------------------------------------------------------------------------------------
then, I found the files glance-api-paste.ini and glance-registry-paste.ini are empty:

[root@test glance]# ll /etc/glance/
total 140
-rw-r----- 1 glance glance 54820 Feb 17 10:28 glance-api.conf
**-rw-r----- 1 glance glance     0 Feb 17 10:28 glance-api-paste.ini**
-rw-r----- 1 glance glance 10494 Feb 17 10:28 glance-cache.conf
-rw-r----- 1 glance glance 43963 Feb 17 10:28 glance-registry.conf
**-rw-r----- 1 glance glance     0 Feb 17 10:28 glance-registry-paste.ini**
-rw-r----- 1 root   glance 15220 Feb  5 15:32 glance-scrubber.conf
drwxr-xr-x 2 root   root    4096 Feb 17 10:23 metadefs
-rw-r----- 1 root   glance  1311 Dec 21 22:51 policy.json
-rw-r----- 1 root   glance  1279 Dec 21 22:51 schema-image.json

[root@test yum.repos.d]# cat rdo-release.repo 
[openstack-liberty]
name=OpenStack Liberty Repository
baseurl=http://mirror.centos.org/centos/7/cloud/$basearch/openstack-liberty/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Cloud

please fix this bug, thanks!

**Comment by chenleji** [comment]
I think i have found the root cause. The glance-*-paste.ini was move to /usr/share/glance/, but the *.conf still use the default path of *-paste.ini (/etc/glance/glance-*-paste.ini).

**Comment by apevec** [comment]
Please open bugs in bugzilla.redhat.com, product "RDO", github issues here are for the rdoproject.org website content only.
That said, paste.inis for glance are in /usr/share/ since ever and pointer to them is in default distro config files e.g. https://github.com/openstack-packages/glance/blob/rdo-liberty/glance-registry-dist.conf#L19
Was this clean install i.e. there wasn't any pip installed python packages on the box?

**Comment by chenleji** [comment]
thanks! I will try again.
