### ISSUE TITLE
Rename Delorean to DLRN

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#400]
Update docs to reflect Delorean -> Fluzo name change, as decided in Feb 24 meeting.

**Comment by rbowen** [comment]
On hold, pending a new name.

**Comment by leifmadsen** [comment]
I started working on some of this. Doesn't look too bad. Some of the work is going to be around this repository and making sure the commands are updated from `delorean` to `dlrn` (which is a nice side effect of this rename since it'll be less chars :))

https://github.com/openstack-packages/DLRN

**Comment by apevec** [comment]
WIP rename in openstack-packages/delorean https://review.gerrithub.io/269944

NB repo was renamed only in github, it requires re-import in gerrithub which isn't transparent like github rename. Instead of that, we should migrate to rpmfactory directly using the new name.

**Comment by rbowen** [comment]
https://trunk.rdoproject.org/ also refers to 'delorean'.

**Comment by apevec** [comment]
trunk landing page fixed in https://github.com/redhat-openstack/trunk.rdoproject.org/commit/27f6ef3c72bd2937276be5070f747564778bb99f

**Comment by rbowen** [comment]
All remaining references to 'delorean' are under the tripleo directory (except for blog posts and testdays, which we don't need to update, as they are historical).

**Comment by rbowen** [comment]
Done
