### ISSUE TITLE
ERROR : Error appeared during Puppet run: 192.168.0.145_cinder.pp

### ISSUE THREAD

**Issue by AJNOURI** [redhat-openstack/website#466]
Having this error when trying to install openstack allinone (https://www.rdoproject.org/):

`packstack --allinone`

**/var/tmp/packstack/20160314-225237-3Q9SBI/openstack-setup.log**

> ...
> tar --dereference -cpzf - ../manifests | ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@19
> 2.168.0.145 tar -C /var/tmp/packstack/fd4a92cb19844851b8a15479efaf3827 -xpzf -
> cd /usr/share/openstack-puppet/modules
> tar --dereference -cpzf - apache ceilometer certmonger cinder concat firewall glance galera heat horizon inifile
>  ironic keystone manila memcached mongodb mysql neutron nova nssdb openstack packstack qpid rabbitmq redis remote rsync sahara ssh stdlib swift sysctl tempest trove vcsrepo vlan vswitch xinetd openstacklib | ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@192.168.0.145 tar -C /var/tmp/packstack/fd4a92cb19844851b8a15479efaf3827/modules -xpzf -
> 2016-03-14 22:55:26::ERROR::run_setup::1017::root:: Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 992, in main
>     single_step_aio_install(options, logFile)
>   File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 760, in single_step_aio_install
>     single_step_install(options, logFile)
>   File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 791, in single_step_install
>     _main(options, answerfilepath, logFile)
>   File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 660, in _main
>     runSequences()
>   File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 627, in runSequences
>     controller.runAllSequences()
>   File "/usr/lib/python2.7/site-packages/packstack/installer/setup_controller.py", line 81, in runAllSequences
>     sequence.run(config=self.CONF, messages=self.MESSAGES)
>   File "/usr/lib/python2.7/site-packages/packstack/installer/core/sequences.py", line 109, in run
>     step.run(config=config, messages=messages)
>   File "/usr/lib/python2.7/site-packages/packstack/installer/core/sequences.py", line 50, in run
>     self.function(config, messages)
>   File "/usr/lib/python2.7/site-packages/packstack/plugins/puppet_950.py", line 209, in apply_puppet_manifest
>     wait_for_puppet(currently_running, messages)
>   File "/usr/lib/python2.7/site-packages/packstack/plugins/puppet_950.py", line 123, in wait_for_puppet
>     validate_logfile(log)
>   File "/usr/lib/python2.7/site-packages/packstack/modules/puppet.py", line 107, in validate_logfile
>     raise PuppetError(message)
> PuppetError: Error appeared during Puppet run: 192.168.0.145_cinder.pp
> Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install openstack-cinder' returned 1: Error: Package: 1:python-cinder-7.0.1-1.el7.noarch (openstack-liberty)

**Comment by AJNOURI** [comment]
Actually **20160314-225237-3Q9SBI/manifests/192.168.0.145_cinder.pp.log** shows that python-cheetah requirement is not satisfied

> Error: NetworkManager is not running.
> Warning: Scope(Class[Cinder]): Could not look up qualified variable '::cinder::params::lock_path'; class ::cinder::params has not been evaluated
> Notice: Compiled catalog for localhost in environment production in 1.05 seconds
> Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
>    (at /usr/share/ruby/vendor_ruby/puppet/type.rb:816:in `set_default')
> Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install openstack-cinder' returned 1: Error: Package: 1:python-cinder-7.0.1-1.el7.noarch (openstack-liberty)
>            **Requires: python-cheetah**
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> Error: /Stage[main]/Cinder/Package[cinder]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install openstack-cinder' returned 1: Error: Package: 1:python-cinder-7.0.1-1.el7.noarch (openstack-liberty)
>            Requires: python-cheetah
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> 

Cannot find this package through subscribed repository nor local DVD. 
Couls find src.rpm file but the dependency chain seems undefinite...

Any hint how to install this python-cheetah?

**Comment by apevec** [comment]
First of all, this is the issue tracker for _website_ NOT support forum.
You can get involved w/ RDO community via IRC, rdo-list or ask.openstack.org as listed in https://www.rdoproject.org/community/ - please restate your issue in one of those channels!

Regarding the reported issue, I guess you're running on RHEL7 in which case please see "Optional, Extras, and RH Common channels" in https://www.rdoproject.org/documentation/repositories/
