### ISSUE TITLE
Need RSS/Atom for Blog

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#5]
One of the ways that we publish our stories to the larger community is via planet.openstack.org which consumes the RSS feed from rdoproject.org/blog

So, we need http://beta.rdoproject.org/blog/ to produce an RSS feed for that purpose.

**Comment by garrett** [comment]
I can't get to the website right now, but it's there as:

http://beta.rdoproject.org/blog/feed.xml

(It's in the meta of the header.)

Also, I'm not sure why the website is down... :cry: I'll ask Michael.

**Comment by garrett** [comment]
os1, where the RDO beta website is hosted, has a scheduled outage... for 2 days. “Perfect” timing. :disappointed:

**Comment by garrett** [comment]
Since the site is back up (thanks to misc's deployment elsewhere), you can now click the link and see [the feed](http://beta.rdoproject.org/blog/feed.xml) is working. :smile:
