### ISSUE TITLE
./create-post.rb:15:in `<main>': undefined method `parse!' for Slop:Module (NoMethodError)

### ISSUE THREAD

**Issue by chkumar246** [redhat-openstack/website#578]
Steps to reproduce:
[1.] git clone https://https://github.com/redhat-openstack/website.git
[2.] cd website; ./setup.sh
[3.] gem install slop launchy
[4.] [chkumar246@fedora website]$ ./create-post.rb "[Event Report] RDO Bug Triage Day  on 18th and 19th May, 2016"
./create-post.rb:15:in `<main>': undefined method `parse!' for Slop:Module (NoMethodError)

**Comment by garrett** [comment]
You shouldn't `gem install`.

The gems need to be in `Gemfile` (if they're not for whatever reason, that should be considered a bug) and you have to run `bundle install`; it may be the case that the Slop API has changed (again).

**Comment by garrett** [comment]
I just checked... the slop gem is missing from the Gemfile. The command was originally ported from another repo, where it was included in the Gemfile. The command was written to Slop version 3.x, and 4.x broke API compatibility. (See https://github.com/leejarvis/slop#upgrading-from-version-3)

Solution is to add the following in `Gemfile`:

```bundler
gem 'slop', '~> 3' 
```

...and run `bundle install`.

I'll make a pull request to handle this.

**Comment by garrett** [comment]
(BTW: I would update the code to slop version 4, but we're actually depending on a feature they removed. Ruby experts can feel free to look at and update the code to work — it wasn't so trivial when I looked at it.)

**Comment by garrett** [comment]
(Still working on it locally... will submit a new PR with a more proper fix soon.)

**Comment by garrett** [comment]
The new PR adds the correct gems, upgrades `create-post.rb` to slop version 4, and enables one to run it without prefixing it with `bundle exec`.
