### ISSUE TITLE
Doc request: Setting up developer environment

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#609]
Document what is needed to set up a developer environment for RDO:
- What do you need to clone?
- What tools might you need installed?
- What mailing lists should you subscribe to?
- What IRC channels should you be on?
- How do I get my first patch through the process?

**Comment by ununseptium** [comment]
Thats what i wanted to see. 😄 👍

**Comment by rbowen** [comment]
https://www.rdoproject.org/documentation/rdo-packaging/ in fact already covers a lot of this, but it's a very intimidating document. Perhaps better to split it into a few smaller docs?

**Comment by pmkovar** [comment]
Split it into the following subpages?

* RDO OpenStack Packaging (Intro)
* RDO Trunk Packaging Guide
* RDO CloudSIG Packaging Guide

But then again, people might prefer to have a single html for easy searching? 

@yac @amoralej  Your thoughts?

**Comment by pmkovar** [comment]
Also, do we need to have https://www.rdoproject.org/documentation/packaging/ around? I thing the info contained there could go to the front page and links to https://www.rdoproject.org/documentation/?

**Comment by rbowen** [comment]
Yes, I agree, that page is probably no longer valuable.

**Comment by pmkovar** [comment]
From @javierpena: 

https://review.rdoproject.org/etherpad/p/RDO-Documentation

**Comment by snecklifter** [comment]
I think this is well-documented now with the onboarding process and other docs like:

https://www.rdoproject.org/contribute/

so suggest this one is closed?

**Comment by rbowen** [comment]
Agreed. Thanks, all!
