### ISSUE TITLE
Clean up Miscellaneous Docs and Upstream Documentation pages

### ISSUE THREAD

**Issue by pmkovar** [redhat-openstack/website#626]
* https://www.rdoproject.org/documentation/upstream-docs/ can probably be replaced with a single link to docs.o.org (+ https://www.rdoproject.org/documentation/books/)?

* Most of the links in https://www.rdoproject.org/documentation/misc/ are outdated
 * eg. https://www.rdoproject.org/documentation/securing-services/
 * not sure about HA links yet, need to confirm with @javierpena 
 * move https://www.rdoproject.org/rdo/rdo-videos/ et al. to archive?

**Comment by hguemar** [comment]
As for videos, we have newer content:
https://www.youtube.com/playlist?list=PL27cQhFqK1QwGg15Yd4jeZVLtuvyboGSi (e.g FOSDEM day)

**Comment by pmkovar** [comment]
Ok, then we probably want to update the page instead of archiving it. I'd move it under https://www.rdoproject.org/community/, just not sure about the section for it. Stay informed?

**Comment by rbowen** [comment]
Didn't intend to close that. The PR said "partially closes".

**Comment by pmkovar** [comment]
So the status here is we have two pages left in the misc category:

* https://www.rdoproject.org/cloud-management/using-manageiq-on-openstack/
* https://www.rdoproject.org/testday/testing-rdo-with-rally/

@rbowen @hguemar Is there somebody who could help me review those two or confirm they can be safely removed?

**Comment by rbowen** [comment]
While I would like to have manageiq docs, I'm not sure who we need to talk to about this. There's something at http://manageiq.org/documentation/top-tasks/#add-red-hat-openstack-providers and perhaps we should drop our local, outdated doc, and link there instead.

The testing with rally doc, I believe, just needs to go away.
