### ISSUE TITLE
Enhanced footer

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#73]
RDO should probably have a footer similar to one of my original mockups, like so:

![rdo-web-breathe-frontpage-footer](https://cloud.githubusercontent.com/assets/10246/10076091/ce844e2c-62d9-11e5-8abe-59f796660678.png)

Please make a few lists of what you'd like to see there, using this mockup as an example.

**Comment by garrett** [comment]
I've implemented it, but need to know the categories and links, then the PR can be adjusted and (after that) merged.

**Comment by rbowen** [comment]
I've added/altered the necessary links.

**Comment by garrett** [comment]
Now that it's live on Beta, it's not quite right on a full screen — I realize the width is 100%, and it should be constrained like everything else. (I'll cook up a patch for this today.)

**Comment by garrett** [comment]
It's improved in a0b9635eb7cd432058e5c21dc6d18c29f1b1e2d2.

I guess this issue should be closed now?
