### ISSUE TITLE
Split apart theme.sass

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#75]
`theme.sass` is pretty huge and has all the custom styling of the site (sitting on top of other CSS scaffolding). It should, ideally, be separate files to make it a bit easier for follow and maintain.

**Comment by garrett** [comment]
WIP in `sass-theme-split` branch:
https://github.com/redhat-openstack/website/tree/sass-theme-split

**Comment by garrett** [comment]
WIP PR in #103 — it doesn't work yet though. I've been squash-merging changes and force pushing, as it's my own branch and I want it clean (without intermediate states). After all the work I've done on this, I've hit a snag. It works locally, but mysteriously refuses to build. (It's a mystery as the `@extend`s worked fine before and not after.

I was hoping to land this change before the site goes live, so I could build more on top of the changed CSS, and so that others might understand the CSS a bit better too.

**Comment by rbowen** [comment]
So, is this done? Or is it still in process?

**Comment by garrett** [comment]
Well, it was done, except that there's a bug where it doesn't recognize imports in SASS. I haven't been able to figure it out; it might take someone who know Ruby/Rails to get this working. 

And, of course, since then, there have been a lot of changes... so this effort would have to be ported to the latest codebase.

Is there a need to have the files split? I thought it would be nice for understandability and maintenance reasons... but is there an actual _need_ for it?

**Comment by rbowen** [comment]
I don't know if there's a need for it. I don't actually know what the motivation behind this ticket was in the first place.

**Comment by garrett** [comment]
The motivation was to track the split the large bunch of CSS into separate files, and the motivation for splitting into separate files was so that it's easier for others to understand.

Since there's really a blocking bug (that I'm unable to figure out without hugely significant amounts of time or some assistance from a Ruby on Rails expert) and this is just an enhancement, I'll go ahead and just close this issue. (The PR of all the effort in a branch was already closed, FWIW.)
