### ISSUE TITLE
rewrite MediaWiki links in document source

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#750]
The website is still using MediaWiki links. Currently, these are being rewritten on the fly.

Downsides to current approach:

- The MW-based links are fragile, as they're reliant on custom code.
- Build time is increased while rewriting links.
- It's possible that some links that should not be rewritten may be rewritten on accident.
- You don't know what the link will resolve to until the site is built.
- It's impossible to port to any other system in the future.

As a result, I've been working on code that will rewrite the links back into the source files, instead of on-the-fly. (I've applied the rewriting to the oVirt site, as of yesterday, and am working on porting similar changes to the RDO site today.)

I'll post a PR soon.

**Comment by pmkovar** [comment]
@garrett Thanks for working on this. Can we now also remove `redirects.yaml`?

**Comment by garrett** [comment]
@pmkovar: Yes! Good idea. It's not needed anymore. I think .htaccess might reference it, however, so it'd need to be adjusted also.
