### ISSUE TITLE
Events integration with rh-events

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#76]
RDO should have a filtered list of events from the [rh-events repo](https://github.com/OSAS/rh-events/).

**Comment by garrett** [comment]
Merged in first pass... It still needs a few improvements to be complete.

**Comment by garrett** [comment]
### Current events TODO
* [x] Events integration
* [x] Filtering on a talk level
* [ ] Fix calendar widget
* [ ] Style

_…so we're getting there...!_

**Comment by rbowen** [comment]
Looks like this is working now, right?

**Comment by rbowen** [comment]
http://beta.rdoproject.org/events/ lists all of the events, but the hangouts/meetups don't show up in the calendar view. Is that something we can get fixed please? Thanks.

**Comment by garrett** [comment]
It works locally. Also, there are so many items it looks awful.

Here's a truncated screenshot:
![screen shot 2015-10-13 at 09 28 43-2](https://cloud.githubusercontent.com/assets/10246/10448434/2010deb0-718d-11e5-9243-f84521a30c9f.png)

**Comment by rbowen** [comment]
It looks like there were indeed too many events there - it had the entire Meetups.com export for the week for 'OpenStack', many of which are Docker, Ansible, and whatnot. I expect this'll look better now that there's just 2-3 per day.

**Comment by garrett** [comment]
I have a ton of pending changes in the `events-upgrade` branch. It's not ready for merging, and I'll probably rewrite the history and squash a few commits before committing. But it's here, shared on GitHub, so I have a backup (just in case) and so you can see the status.
https://github.com/redhat-openstack/website/compare/events-upgrade?expand=1

It's _mostly_ done now. I have a WIP of the events view on the page (below the calendar) that isn't in the branch — because I'm not happy with it yet. It will all land this week, possibly even tomorrow. (No promises.)

Anyway, it's a huge bunch of changes, and it should handle events (like the amount in the screenshot) in a much better way.

You and I also need to go over optimizing your script so that things are displayed a bit better too. (Like the URL, end times, and such.) But this is probably optional, as I think most of the remaining work that _needs_ to be done before launch for the events calendar is still on my side.

Also, noteworthy: These changes will make their way into the RH Community website and the oVirt conversion too, when this is all done.
