### ISSUE TITLE
Main navigation links

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#78]
Where should the main navigation go? 

What's on beta isn't correct. What's on MediaWiki isn't optimal.

This should be a discussion. (:

You have a maximum about 5 (±1) items. _Go!_

Anything important, but not a landing page, can be linked from the front page and/or in the new footer (#73).

**Comment by garrett** [comment]
Any progress on this?

**Comment by rbowen** [comment]
Perhaps I'm confused as to what this refers to. In what way is the navigation not optimal and/or not correct? It looks right to me.

**Comment by rbowen** [comment]
To answer the question asked, the links should be:

Quickstart -> /quickstart
Docs -> /documentation
Blog -> /blog
Get Involved -> /community
Ask -> http://ask.openstack.org/

Like we have on the current live site.

**Comment by garrett** [comment]
Ask should not be a main navigation item. Main navigation items should never point off to a different site; it's confusing and breaks flow.

**Comment by rbowen** [comment]
Then I guess we're done with this.

**Comment by garrett** [comment]
Oh, I was hoping for a discussion... like if events belongs up there or not, etc.

**Comment by garrett** [comment]
Somewhat related: let's make Ask more prominent. Like in the "Community" / "Get Involved" section. (Also: What should that section really be called?)

And, also, apparently, ask.openstack.org has an API, via AskBot's API:
https://ask.openstack.org/en/api/v1/questions/
(So perhaps we can use it as a landing page on the site and then a way to kick over to the other site? And then it could be in the navigation to get to the local landing page.)

API docs: http://askbot.org/doc/api.html

Also, it could then be integrated into the front page, or on the secondary page, similar to the original mockup's forum intro on the front page:

![rdo-web-breathe-frontpage](https://cloud.githubusercontent.com/assets/10246/10519140/c978e4ec-7364-11e5-80ad-3332f7894bc3.png)

and/or (depending on context) similar to the original forum itself on the local landing page:

![rdo-web-breathe-hylke-3](https://cloud.githubusercontent.com/assets/10246/10519194/07be714a-7365-11e5-83b6-43e9041957fd.png)

---

But at this point, all of the above needs to be filed as a different issue (or issues), really.

**Comment by garrett** [comment]
BTW: The landing page would need to be done before launch, if we want that in the nav. Styling and inclusion on the front page and such could be done after. For launch, the landing page with a blurb and a link would be enough, if that's what's decided.

**Comment by garrett** [comment]
(But *this* is why I opened this issue for a conversation on this topic. It'd be nice to talk about stuff like this over voice at some point, and make a decision, and move forward with the implementation.)

**Comment by rbowen** [comment]
Having Events in the nav could be a nice addition, yes. That's a good idea.

**Comment by garrett** [comment]
(@rbowen: What about the rest of the points I brought up?)

**Comment by rbowen** [comment]
As far as we can tell, everything mentioned in this ticket has been addressed.
