### ISSUE TITLE
Overhaul the main docs page

### ISSUE THREAD

**Issue by garrett** [redhat-openstack/website#79]
- [ ] **Step 1**: Figure out what really should be a set of top-level links.
- [ ] **Step 2**: Organize links.

I'm happy to help with step 2, but I need others to mainly figure out step 1.

**Comment by garrett** [comment]
Any progress forward on this (step 1), @rbowen?

**Comment by rbowen** [comment]
I don't agree that this is a launch blocker. This is a content issue, and will be a moving target, driven by the community. We have a lot better chance of moving this along once the site is live, and/or as part of the documentation sprint.
