### ISSUE TITLE
Remove Gemfile.lock from repo

### ISSUE THREAD

**Issue by javierpena** [redhat-openstack/website#802]
If we clone the source and follow instructions from README.md, we can't start a development middleman because Gemfile.lock was present already, and no gems are installed when calling setup.sh

**Comment by rbowen** [comment]
Garrett and Misc disagree, and say that the lockfile is necessary.

**Comment by rbowen** [comment]
Sorry, I didn't intend to close that.

**Comment by mscherer** [comment]
Yup, I forgot the details, but we need it so we can have reproductible environment. I would have agreed with Javier in theory, but in practice, not having the lock caused too much issue :/

I am gonna try the READMe later, to see the message/error.

**Comment by javierpena** [comment]
Mmm, now it works for me without removing Gemfile.lock. Before it failed because ./run-server.sh could not find the middleman gem.

Anyway, it works now. Nevermind.

**Comment by pmkovar** [comment]
Hitting the same issue here with not being able to find middleman. Removing or updating Gemfile.lock did not help. Any ideas what could be the cause?

**Comment by javierpena** [comment]
What worked for me when I had issues was:

- Remove Gemfile.lock
- Run ./setup.sh
- ./run-server.sh

Optionally, you can create your own directory for the Ruby gems (before running setup.sh):
- mkdir /tmp/gems
- export GEM_HOME=/tmp/gems

**Comment by pmkovar** [comment]
> What worked for me when I had issues was:

Can confirm that it works now but I swear it did not yesterday. Some strange caching issue?

OK to close then?

**Comment by rbowen** [comment]
Closing, per Petr saying that it's working.
