### ISSUE TITLE
Ensure every directory has a top-level index file

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#82]
If there's a foo directory, there should be a foo/ URL, ie, an index file in that directory. At the very least, it should be an overview of what's contained in the directory.

**Comment by garrett** [comment]
I wonder if I could automate this a bit... at the very least, perhaps a special layout that scans the directory and shows the results in a friendly(ish) way. As it would be a layout, you could still edit an index.html.haml file with some additional information above a dynamic (at compile time and also runtime on a local server) page tree.

No promises, however... but I'll look into this today. We'll see what happens. :wink:
