### ISSUE TITLE
"Adding a Compute Node" documentation seems outdated

### ISSUE THREAD

**Issue by berndbausch** [redhat-openstack/website#833]
Thanks for Packstack. I started using it a few days ago and like its simplicity and robustness (with a few quirks) a lot. However the documentation seems occasionally outdated and misleading. Specifically: https://www.rdoproject.org/install/adding-a-compute-node/. 

It says 

> Change both CONFIG_NOVA_COMPUTE_PRIVIF and CONFIG_NOVA_NETWORK_PRIVIF from lo to eth1 or whatever name your network card uses.

The answer file created by my standard --allinone deployment doesn't set these config parameters at all, and given the comment in the answer file "flat DHCP on the Compute network server" I suspect that they are only needed when deploying Nova Network. Thus, I am confused.

Another place that doesn't look quite correct:

> In case you do not want to run the installation over again on the already configured servers, add the following parameter to the "answer file":
> 
>   EXCLUDE_SERVERS=<serverIP>,<serverIP>,...

When I excluded my already installed allinone server, Packstack didn't setup the SSH keys required for live migration. When I included it, keys were set up correctly. Users should be given more information to decide whether exclusion makes sense or not.

**Comment by pmkovar** [comment]
Hi @booxter, could you comment on the suggestions above?

**Comment by booxter** [comment]
@berndbausch you are right that the first suggestion would apply for Nova-Network, and since it's deprecated, we probably should remove the notion from RDO docs. Ideally you would propose a PR for the documentation page that would describe your actual experience more closely.

As for the latter point, I don't know exactly what it's supposed to mean, it's packstack specific. @pmkovar I suggest to reach out to packstack folks for details on that latter point.

**Comment by berndbausch** [comment]
"Ideally you would propose a PR for the documentation page" 

I wouldn't mind doing that, but what is a PR and how do I propose one?

Perhaps it's best I make the second point clearer. 

I created an allinone server first, then added a second node (a compute node). Since I thought that the allinone server was already installed, I added it to the EXCLUDE_SERVERS list. As a result, the configuration on the allinone server was not adapted to the new two-node setup. 

Therefore my suggestion: Make it clear what I gain when adding a server to EXCLUDE_SERVERS, and under which circumstances it's save to do so. If there is little or nothing to gain, I would remove this part from the documentation to avoid confusing people like me.

**Comment by pmkovar** [comment]
@berndbausch 

> I wouldn't mind doing that, but what is a PR and how do I propose one?

The standard workflow is to fork the https://github.com/redhat-openstack/website repository, make your changes in the fork, and then submit your changes by creating a Pull Request, as described in https://help.github.com/articles/creating-a-pull-request-from-a-fork/.

**Comment by javierpena** [comment]
@berndbausch the page was quite outdated, I have proposed a PR to add a note about EXCLUDED_SERVERS and update the instructions to reflect the current usage of Neutron instead of Nova Network.

Thanks for the report!
