### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#92]
I'm seeing CI failures on most of my merges, and they all look something like the following.

$ cd redhat-openstack/website
3.45s$ git fetch origin +refs/pull/91/merge:
fatal: Couldn't find remote ref refs/pull/91/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/91/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/91/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/91/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/91/merge
Unexpected end of command stream
The command "eval git fetch origin +refs/pull/91/merge:" failed 3 times.
The command "git fetch origin +refs/pull/91/merge:" failed and exited with 128 during .
Your build has been stopped.

**Comment by garrett** [comment]
The latest in master builds here locally, so this is probably for @mscherer.

**Comment by mscherer** [comment]
Can you give a link ?

**Comment by garrett** [comment]
FWIW, it worked fine for me after pushing my offline changes Friday, on Friday evening, from this PR:
https://github.com/redhat-openstack/website/pull/95

The CI links were:
https://travis-ci.org/redhat-openstack/website/builds/82196152
https://travis-ci.org/redhat-openstack/website/builds/82194899

(Note: PR #95 is not meant to be merged yet. I am awaiting content from @rbowen first; this is related to issue #73.)

**Comment by mscherer** [comment]
I suspect travis had some issues, but I do not have control on it.

**Comment by garrett** [comment]
Closing this as a “**WORKSFORME**”, as I've done some PRs since, and noticed @rbowen has also. I guess it was a temporary hiccup that doesn't happen under normal circumstances.

**Comment by garrett** [comment]
(If I'm mistaken, please reopen with details.)
