### ISSUE TITLE
Simplify and subdivide "/community" page

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#927]
https://www.rdoproject.org/community/ has grown unwieldy and unfocused. The entire RDO site is "community", so it may not even be necessary as a top-level change.

Perhaps we can drop the "Community" link from the nav bar, and instead focus on "Users" and "Developers" as top-level nav concepts?

Either way, this page needs to be split into sub-pages if it is to remain here at all. It's just a huge wall of text.

**Comment by pmkovar** [comment]
@rbowen I guess the new Developers page should also point to conceptual pages from #908? Those pages seem all to be developer-centric.
