### ISSUE TITLE
Rearrange top level navigation

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#928]
Current top level navigation:

Home
Blog
Events
Community
Docs

I would propose something more like:

Home
Use
Contribute
Events
Blog

This separates "Community" into users and developers.

Thoughts?

**Comment by pmkovar** [comment]
I like it. 

We would retain "Search" as a top level link, too, I guess.

> This separates "Community" into users and developers.

Which would be addressed in #927.

**Comment by rbowen** [comment]
and of course we'd actually need to create the places that those two new pages point ...
