### ISSUE TITLE
Clearly define Packstack and TripleO QS pages to remove confusion

### ISSUE THREAD

**Issue by cbrown2** [redhat-openstack/website#931]
Per title, the packstack page is:

https://www.rdoproject.org/install/quickstart/

and is called Packstack quickstart. Very confusing to a newcomer.

**Comment by rbowen** [comment]
What do you think it should be called instead?

**Comment by cbrown2** [comment]
https://www.rdoproject.org/install/packstack

**Comment by rbowen** [comment]
Ah, ok, so you want to change the URL also. Got it.

Meanwhile, you also want to have the term "quickstart" refer exclusively to the TripleO QuickStart, and not use that for packstack any more. Got it. (I'm a little slow. ;-) )

**Comment by cbrown2** [comment]
Yes, spot on. Its the two packages/tools both using the "quickstart" term that is the problem for me (and others I think).

**Comment by rbowen** [comment]
See also https://www.redhat.com/archives/rdo-list/2017-June/msg00027.html

**Comment by cbrown2** [comment]
Looks like this has been addressed so closing.
